apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
  namespace: saas
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: saas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0.9-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          command: [ "sh", "-c", "redis-server --requirepass test1234" ]