apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: external-resource
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb-svc
  namespace: external-resource
subsets:
  - addresses:
      - ip: 192.168.123.123
    ports:
      - port: 27017
