# 192.168.1.103
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: external-resource
spec:
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: http-api
      port: 15672
      targetPort: 15672

---

apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq-svc
  namespace: external-resource
subsets:
  - addresses:
      - ip: 192.168.123.123
    ports:
      - port: 5672
        name: amqp
      - port: 15672
        name: http-api

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-svc
  namespace: external-resource
spec:
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672

---

apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq-management-svc
  namespace: external-resource
subsets:
  - addresses:
      - ip: 192.168.123.123
    ports:
      - port: 15672

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management-ingress
  namespace: external-resource
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "mq.dev-k8s.sample.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-management-svc
                port:
                  number: 15672
