apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: deploy
spec:
  #storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: deploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: jenkins-pv
  #storageClassName: ""
  selector:
    matchLabels:
      purpose: jenkins-shared-deployement