apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: deploy
spec:
  type: ClusterIP
  selector:
    app: jenkins
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: slave
    port: 5000
    targetPort: 5000
    protocol: TCP