apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: database
data:
  mysql.cnf: |
    [client]
    default-character-set=utf8
  
    [mysql]
    default-character-set=utf8
    bind-address="0.0.0.0"