apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web-pod
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: app-sample:dev-test
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Asia/Seoul"
          volumeMounts:
            # web mount
            - name: app-nas-pvc01
              mountPath: /home/web01/data
            - name: app-nas-pvc02
              mountPath: /home/web02/data
              subPath: data
            - name: app-nas-pvc01
              mountPath: /home/web/application/cache/temp
              subPath: temp
            # api log mount
            - name: app-nas-pvc01
              mountPath: /home/customer/api/logs/
              subPath: api/logs/
            - name: app-nas-pvc01
              mountPath: /home/customer/data
            - name: app-nas-pvc01
              mountPath: /home/customer/
              subPath: data
            # admin data mount
            - name: app-nas-pvc02
              mountPath: /home/admin/data
            - name: app-nas-pvc02
              mountPath: /home/admin/api/data
            - name: app-nas-pvc02
              mountPath: /home/admin/api/logs
              subPath: logs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: app-nas-pvc01
          persistentVolumeClaim:
            claimName: app-nas-pvc01
        - name: app-nas-pvc02
          persistentVolumeClaim:
            claimName: app-nas-pvc02