apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-nas-pv01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.111.111
    path: /home/nas01/
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-nas-pv02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.112.112
    path: /home/nas02/

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-nas-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: app-nas-pv01

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-nas-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: app-nas-pv02
