apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: database
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 30306
  selector:
   app: postgres