apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: kafka
spec:
  #storageClassName: 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kafka/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-volume-claim
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: kafka-pv
  #storageClassName: ""
  selector:
    matchLabels:
      purpose: kafka-shared-deployement