apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: monitoring
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      # Refers to our previously defined ServiceAccount.
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.6.2
          args: [
              "-c", "/etc/filebeat.yml",
              "-e",
          ]
          env:
            - name: LOGSTASH_URL
              value: "172.27.0.4:5044"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            # spec.volumes 과 한쌍
            # k8s 로그는 각 노드 host 의 /var/log/containers/*.log 로 생성된다. filebeat ConfigMap 의 paths 에 이 경로로 설정되어있음
            - name: varlog
              mountPath: /var/log
              readOnly: true
            # docker 컨테이너 로그 경로 마운트 (/lib/systemd/system/docker.service > dockerd -g 옵션 확임)
            # 각 k8s 노드에 설치한 [docker 홈경로]/containers 로 지정
            # /var/log/containers/*.log 는 심볼릭 링크이고 실제로는 각 노드의 [docker 홈경로]/containers/ 하위파일을 가리키고있음
            - name: datadockercontainers
              mountPath: /data/docker/containers
              readOnly: true
            # filebeat-config ConfigMap 을 각 filebeat Pod 컨테이너에 Mount
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            # filebeat Pod 에서 사용하는 저장(유지)되어야 하는 데이터 저장 경로 Mount
            - name: data
              mountPath: /usr/share/filebeat/data
      volumes:
        - name: datadockercontainers
          hostPath:
            path: /data/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            defaultMode: 0600
            name: filebeat-config
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate