apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: login
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:latest
        env:
        - name: KEYCLOAK_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: username
        - name: KEYCLOAK_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: password
        envFrom:
        - configMapRef:
            name: keycloak-config
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080