apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  namespace: login
  labels:
    app: keycloak
spec:
  ports:
  - name: https
    port: 30443
    targetPort: 30443
    # nodePort: 31443 # doesn't work
  - name: http
    port: 30080
    targetPort: 30080
    nodePort: 31080
  selector:
    app: keycloak
  type: NodePort