{
 "title": "K8S Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "Node",
    "query": "label_values(kube_pod_info{cluster=~\"^$Cluster\"}, node)"
   },
   {
    "name": "Namespace",
    "query": "label_values(kube_pod_info{cluster=\"$Cluster\"}, namespace)"
   },
   {
    "name": "Workload",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"^$Namespace\"}, workload)"
   },
   {
    "name": "Type",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"^$Namespace\", workload=~\"^$Workload\"}, workload_type)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{node=~\"^$Node\", namespace=~\"^$Namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\"}[2m])) / sum (sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"})) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\", container!=\"\"}) / sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{deployment=~\".*$Workload\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Workload\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Workload\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{deployment=~\".*$Workload\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Workload\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Workload\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{deployment=~\".*$Workload\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Workload\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Workload\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\", container!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_memory_bytes{node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{deployment=~\".*$Workload\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{statefulset=~\".*$Workload\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{daemonset=~\".*$Workload\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{deployment=~\".*$Workload\"}) or vector(0)) + (sum(kube_statefulset_replicas{statefulset=~\".*$Workload\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\".*$Workload\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "Replica Count (Deployment only)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{cluster=~\"^$Cluster\", namespace=~\"^$Namespace\", deployment=~\"^$Workload.*$\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\"}\r\n  * on(namespace,pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"^$Namespace\", workload=~\"^$Workload\", workload_type=~\"^$Type\"}\r\n) by (node, namespace, pod)",
     "legendFormat": "{{ node }} | {{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    container_memory_working_set_bytes{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\", container!=\"\", image!=\"\"}\r\n  * on(namespace,pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"^$Namespace\", workload=~\"^$Workload\", workload_type=~\"^$Type\"}\r\n) by (node, namespace, pod)",
     "legendFormat": "{{ node }} | {{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O (Pod)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    irate(container_network_receive_bytes_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\"}[$__rate_interval])\r\n  * on (namespace, pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"$Namespace\", workload=~\"$Workload\", workload_type=~\"^$Type\"}\r\n) by (node, namespace, pod)",
     "legendFormat": "Ｉ >  {{ node }} | {{ namespace }} | {{ pod }}"
    },
    {
     "expr": "- sum(\r\n    irate(container_network_transmit_bytes_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\", pod=~\"^$Pod$\"}[$__rate_interval])\r\n  * on (namespace, pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"$Namespace\", workload=~\"$Workload\", workload_type=~\"^$Type\"}\r\n) by (node, namespace, pod)",
     "legendFormat": "Ｏ <  {{ node }} | {{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O (Node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(\r\n    irate(container_network_receive_bytes_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\"}[$__rate_interval])\r\n  * on (namespace, pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"$Namespace\", workload=~\"$Workload\", workload_type=~\"^$Type\"}\r\n) by (node)",
     "legendFormat": "Ｉ >  {{ node }}"
    },
    {
     "expr": "- sum(\r\n    irate(container_network_transmit_bytes_total{cluster=~\"^$Cluster\", node=~\"^$Node\", namespace=~\"^$Namespace\"}[$__rate_interval])\r\n  * on (namespace, pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"^$Cluster\", namespace=~\"$Namespace\", workload=~\"$Workload\", workload_type=~\"^$Type\"}\r\n) by (node)",
     "legendFormat": "Ｏ <  {{ node }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})\r",
     "legendFormat": "{{ persistentvolumeclaim }} | {{ kubernetes_io_hostname }}"
    }
   ]
  }
 ]
}